---
- name: create wordpress instance
  hosts: localhost
  connection: local
  gather_facts: no
  become: true
  become_method: sudo
  tasks:
    - name: create ec2
      ec2:
        aws_access_key:
        aws_secret_key:
        region:
        
