---
- name: create wordpress instance
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: create ec2
      ec2:
        aws_access_key:       #계정의 액세스키
        aws_secret_key:       #계정의 비밀 액세스키(적용하지 않으면 default 값 적용)
        key_name:  #인스턴스에 사용할 키페어 이름
        region: ap-northeast-2
        image: 
        instance_type: t2.micro
        group: #보안그룹
        vpc_subnet_id: 
        assign_public_ip: yes
        count: 1
        wait: true
