---
- name: execute shell script
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  connect: local
  gather_facts: no
  tasks:
    - name: execute
      command: sh ~/execute_playbook.sh
