---
- name: configuration web db servers
  hosts: localhost
  gather_facts: no
  vars:
    user: 
    service_account_email: joy-900@project-manageiq.iam.gserviceaccount.com
    credentials_file: /home/heesung6809/project-manageiq-ee12388141f5.json
    project_id: project-manageiq
    web_tag: http-server
    web_image: project-web-wordpress
    web_hc: http-health-check
    web_template: web-tmp
    web_region1: us-central1
    web_region2: asia-northeast1
    backend_service: http-backend-svc
    http_lb: http-lb
    http_proxy: http-proxy
    http_frontend: http-frontend  
  tasks:  
    - name: create instance template
      gce_instance_template:
        name: "{{ web_template }}"
        size: n1-standard-1
        image: "{{ web_image }}"
        state: present
        project_id: "{{ project_id }}"
        credentials_file: "{{ credentials_file }}"
        service_account_email: "{{ service_account_email }}"
        tags: "{{ web_tag }}"
        
##
    - name: create a HTTP health check
      gcp_compute_http_health_check:
        name: "{{ web_hc }}"
        healthy_threshold: 10
        port: 80
        timeout_sec: 2
        unhealthy_threshold: 5
        project: "{{ project_id }}"
        auth_kind: serviceaccount
        service_account_file: "{{ service_account_email }}"
        state: present
##
        
        
    - name: create a health check
      gcp_compute_health_check:
        name: "{{ web_hc }}"
        type: TCP
        tcp_health_check:
          port_name: http
          request: ping
          response: pong
        healthy_threshold: 10
        timeout_sec: 2
        unhealthy_threshold: 5
        project: "{{ project_id }}"
        auth_kind: serviceaccount
        service_account_file: "{{ credentials_file }}"
        state: present
        
    - name: Create MIG to us-central1
      gce_mig:
        project_id: "{{ project_id }}"
        credentials_file: "{{ credentials_file }}"
        service_account_email: "{{ service_account_email }}"
        name: "{{ web_region1 }}-wig"
        zone: "{{ web_region1 }}-a"
        state: present
        size: 1
        template: "{{ web_template }}"
        named_ports:
        - name: http
          port: 80
        recreate_instances: yes
        autoscaling:
          enabled: yes
          name: "{{ web_region1 }}-wig"
          policy:
            min_instances: 1
            max_instances: 5
            cool_down_period: 45
            load_balancing_utilization:
              target: 0.8

    - name: Create MIG to asia-northwest1
      gce_mig:
        project_id: "{{ project_id }}"
        credentials_file: "{{ credentials_file }}"
        service_account_email: "{{ service_account_email }}"
        name: "{{ web_region2 }}-wig"
        zone: "{{ web_region2 }}-a"
        state: present
        size: 1
        template: "{{ web_template }}"
        named_ports:
        - name: http
          port: 80
        recreate_instances: yes
        autoscaling:
          enabled: yes
          name: "{{ web_region2 }}-wig"
          policy:
            min_instances: 1
            max_instances: 5
            cool_down_period: 45
            load_balancing_utilization:
              target: 0.8

    - name: Create BES with extended backend parameters
      gcp_backend_service:
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        backend_service_name: "{{ backend_service }}"
        backends:
        - instance_group: "{{ web_region1 }}-wig"
        - instance_group: "{{ web_region2 }}-wig"
        healthchecks:
        - "{{ web_hc }}"
        port_name: http
        protocol: HTTP
        state: present
        timeout: 60
    
    - name: Create Minimal Url_Map
      gcp_url_map:
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        url_map_name: "{{ http_lb }}"
        default_service: "{{ backend_service }}"
        state: present
        
    - name: Create Minimum HTTP Target_Proxy
      gcp_target_proxy:
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        target_proxy_name: "{{ http_proxy }}"
        target_proxy_type: HTTP
        url_map_name: "{{ http_lb }}"
        state: present
        
    - name: Create Minimum GLOBAL Forwarding_Rule
      gcp_forwarding_rule:
        service_account_email: "{{ service_account_email }}"
        credentials_file: "{{ credentials_file }}"
        project_id: "{{ project_id }}"
        forwarding_rule_name: "{{ http_frontend }}"
        protocol: TCP
        port_range: 80
        region: global
        target: "{{ http_proxy }}"
        state: present
        

