---
- name: configuration web db servers
  hosts: localhost
  gather_facts: no
  vars:
    web_tag: http-server
    web_image: project-web-wordpress
    web_hc: http-health-check
    web_template: web-tmp
    web_region1: us-central1
    web_region2: asia-northeast1
    backend_service: http-backend-svc
    http_lb: http-lb
    http_proxy: http-proxy
    http_frontend: http-frontend  
  tasks:  
    - name: create instance template
      gce_instance_template:
        name: {{ web-tmp }}
        size: n1-standard-1
        image: {{ web_image }}
        state: present
        project_id: "project-manageiq"
        credentials_file: "/home/$USER/project-manageiq-ee12388141f5.json"
        service_account_email: "joy-900@project-manageiq.iam.gserviceaccount.com"
        tags: {{ web_tag }}
        
