---
- name: configuration db VM instance
  hosts: localhost
  become: true
  gather_facts: no
  vars:
    db_tag: mysql
    db_template: db-tmp
    db_image: project-db-snap
    db_region1: us-central1
    db_name: db-server
    db_address: 104.198.255.162
  tasks:
    - name: create instance template
      command: gcloud compute instance-templates create {{ db_template }} --tags=mysql --image={{ db_image }} --scopes=default
      
    - name: create instnace VM
      command: gcloud compute instances create {{ db_name }} --source-instance-template={{ db_template }} --tags=mysql --scope=default --address={{ db_address }}
