- name: create template
  command: gcloud compute instance-templates create {{ tname }} --boot-disk-auto-delete --boot-disk-size=10GB --image={{ image }} --tags={{ tags }}
   
- name: create db server
  command: gcloud compute instances create {{ name }} --source-instance-template={{ tname }} --address={{ exip }} --scopes=default,sql,storage-rw
