---
- name: configuration web db servers
  hosts: localhost
  gather_facts: no
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: configuration web
      import_tasks: web-playbook.yml

