---
- name: create lb
  hosts: localhost
  gather_facts: no
  become: true
  vars_files:
    - vars.yml
  tasks:
    - name: create backend service
      command: gcloud compute backend-services create {{ backend_service }} --global --health-checks={{ web_hc }} --protocol=HTTP --port-name=http --connection-draining-timeout=60

    - name: add backend1
      command: gcloud compute backend-services add-backend {{ backend_service }} --instance-group={{ web_region1 }}-wig --instance-group-region={{ web_region1 }} --balancing-mode=RATE --max-rate-per-instance=100 --capacity-scaler=0.8 --global

    - name: add backend2
      command: gcloud compute backend-services add-backend {{ backend_service }} --instance-group={{ web_region2 }}-wig --instance-group-region={{ web_region2 }} --balancing-mode=RATE --max-rate-per-instance=100 --capacity-scaler=0.8 --global
