---
apiVersion: v1
kind: ReplicationController
metadata:
  name: cccr-rc
  labels:
    app: web
spec:
  replicas: 4
  selector:
    app: web
  template: 
    metadata:
      name: cccr-rc-pod
      labels:
        app: web
    spec: 
      containers:
        - name: rccon
          image: c1t1d0s7/cccr
          ports: 
            - containerPort: 8080