---
- name: create web server 
  hosts: localhost
  gather_facts: no
  vars_files:
    - var.yml
  tasks:
    - name: create
      include_tasks: playbook2.yml

- name: create db server
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: create2
      include_tasks: playbook4.yml
